before:
  hooks:
    - go mod tidy -v
builds:
  - id: nezha-agent
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    main: ./cmd/agent
release:
  name_template: "nezha-agent_{{.Os}}_{{.Arch}}"
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
