before:
  hooks:
    - go get -v .
builds:
  - id: nezha-agent
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    main: ./cmd/agent
    binary: nezha-agent
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{.ProjectName}}"
archives:
  - name_template: "nezha-agent_{{ .Os }}_{{ .Arch }}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
