name: Agent release

on:
  push:
    paths-ignore:
      - "script/**"
      - ".gitignore"
      - "*.md"
      - "cmd/dashboard/**"
      - ".github/workflows/dashboard.yml"
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Go latest version
        uses: actions/setup-go@v2
      - run: |
          go mod vendor
          mkdir -p /home/runner/go/src/
          mv ./vendor/* /home/runner/go/src/
          git checkout .
          mkdir -p /home/runner/go/src/github.com/naiba/nezha
          cp -r ../nezha /home/runner/go/src/github.com/naiba/
          find /home/runner/go/src/ -name "*riscv*.go" -exec rm -rf {} \;
      - name: Set up Go 1.10.8
        uses: actions/setup-go@v2
        with:
          go-version: 1.10.8
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
