name: Agent release

on:
  push:
    paths-ignore:
      - "script/**"
      - ".gitignore"
      - "*.md"
      - "cmd/dashboard/**"
      - ".github/workflows/dashboard.yaml"
    tags:
      - "v*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.10.8
      - run: |
          mkdir -p /home/runner/go/src/github.com/StackExchange/
          cd /home/runner/go/src/github.com/StackExchange/
          git clone https://github.com/StackExchange/wmi.git
          mkdir -p /home/runner/go/src/github.com/inconshreveable/
          cd /home/runner/go/src/github.com/inconshreveable/
          git clone https://github.com/inconshreveable/mousetrap.git
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
