name: Build Docker Image

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Log into registry
        run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: docker
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/nezha-agent -f Dockerfile.agent .
          docker build -t ghcr.io/${{ github.repository_owner }}/nezha-dashboard -f Dockerfile.dashboard .
          docker push ghcr.io/${{ github.repository_owner }}/nezha-agent
          docker push ghcr.io/${{ github.repository_owner }}/nezha-dashboard
