name: Run Test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - uses: actions/checkout@v2
      - name: Unit test
        run: |
          go test -v ./...
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: ./...
