name: Run Tests

on:
  push:
    branches:
      - master
    paths-ignore:
      - ".github/workflows/codeql-analysis.yml"
      - ".github/workflows/test-on-pr.yml"
      - ".github/workflows/contributors.yml"
      - ".github/workflows/sync.yml"
      - ".github/workflows/release.yml"
      - "README.md"
      - ".goreleaser.yml"

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: "^1.21.3"
      - name: Unit test
        run: |
          go test -v ./...
      - name: Build test
        run: |
          go build cmd/dashboard/main.go
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args: --exclude=G104,G402 ./...
